#!/bin/sh

MIRROR_DEBIAN="http://cdn.debian.net/debian/"
MIRROR_SECURITY="http://security.debian.org/"
MIRROR_BOOTSTRAP=${MIRROR_DEBIAN}
MIRROR_VOLATILE=${MIRROR_DEBIAN}

DISTRIBUTION="squeeze"
ARCH="i386"

lb config noauto \
	--apt-recommends true \
	--archive-areas "main" \
	--architecture ${ARCH} \
	--backports false \
	--binary-images iso-hybrid \
	--bootloader syslinux \
	--debian-installer live \
	--debian-installer-distribution ${DISTRIBUTION} \
	--iso-publisher "Debian JP Project; http://www.debian.or.jp/;" \
	--linux-flavours 686 \
	--mirror-binary ${MIRROR_DEBIAN} \
	--mirror-binary-security ${MIRROR_SECURITY} \
	--mirror-binary-volatile ${MIRROR_VOLATILE} \
	--mirror-bootstrap ${MIRROR_BOOTSTRAP} \
	--mirror-chroot ${MIRROR_DEBIAN} \
	--mirror-chroot-security ${MIRROR_SECURITY} \
	--mirror-chroot-volatile ${MIRROR_VOLATILE} \
	--security true \
	--tasks "japanese japanese-desktop japanese-gnome-desktop gnome desktop laptop" \
	--tasksel aptitude \
	--volatile false \
	--win32-loader true \
	-d ${DISTRIBUTION} \
	-l ja \
	-r live.debian.net \
	--net-root-server "192.168.10.11" \
	--net-root-path "/srv/debian-live" \
	${@}
