#!/bin/sh

MIRROR_DEBIAN="http://cdn.debian.net/debian/"
MIRROR_SECURITY="http://security.geo.debian.org/"

lh config noautoconfig \
	--apt-recommends false \
	--archive-areas "main" \
	--bootloader syslinux \
	--debian-installer live \
	--debian-installer-distribution daily \
	--iso-publisher "Debian JP Project; http://www.debian.or.jp/;" \
	--language ja \
	--mirror-binary ${MIRROR_DEBIAN} \
	--mirror-binary-security ${MIRROR_SECURITY} \
	--mirror-bootstrap ${MIRROR_DEBIAN} \
	--mirror-chroot ${MIRROR_DEBIAN} \
	--mirror-chroot-security ${MIRROR_SECURITY} \
	--syslinux-menu vesamenu \
	--syslinux-timeout 15 \
    --linux-flavours 486 \
	${@}
