#!/bin/sh

#MIRROR_DEBIAN="http://ftp.tw.debian.org/debian/"
MIRROR_DEBIAN="http://cdn.debian.net/debian/"
MIRROR_SECURITY="http://security.debian.org/"

lh_config noautoconfig \
	--apt-recommends disabled \
	--categories "main" \
	--debian-installer live \
	--debian-installer-distribution daily \
	--iso-publisher "Debian JP Project; http://www.debian.or.jp/;" \
	--language ja \
	--mirror-binary ${MIRROR_DEBIAN} \
	--mirror-binary-security ${MIRROR_SECURITY} \
	--mirror-bootstrap ${MIRROR_DEBIAN} \
	--mirror-chroot ${MIRROR_DEBIAN} \
	--mirror-chroot-security ${MIRROR_SECURITY} \
	--bootloader syslinux \
	--syslinux-menu vesamenu \
	--syslinux-timeout 15 \
	${@}
